# Generated by Django 3.0.7 on 2020-07-15 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('serialized_cart', models.TextField(verbose_name='序列化的購物車')),
                ('total_amount', models.PositiveIntegerField(verbose_name='總價')),
                ('product_title', models.TextField(verbose_name='商品名以#分隔')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=20, verbose_name='廠商交易編號')),
                ('is_success', models.BooleanField(default=False, verbose_name='交易是否成功')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('check_mac_value', models.TextField(default='', max_length=20, verbose_name='檢查碼')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'get_latest_by': 'datetime_create',
            },
        ),
    ]
