# Generated by Django 3.0.7 on 2020-07-23 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_cart', models.TextField(verbose_name='序列化的購物車')),
                ('total_amount', models.PositiveIntegerField(verbose_name='總價')),
                ('product_title', models.TextField(verbose_name='商品名以#分隔')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=20, verbose_name='廠商交易編號')),
                ('type', models.CharField(choices=[('Credit', '信用卡及 GooglePay'), ('GooglePay', 'GooglePay'), ('WebATM', '網路 ATM'), ('ATM', '自動櫃員機'), ('CVS', '超商代碼'), ('BARCODE', '超商條碼'), ('ALL', '不指定付款方式，由綠界顯示付款方式選擇頁面。')], default='Credit', max_length=9)),
                ('is_success', models.BooleanField(default=False, verbose_name='交易是否成功')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'ordering': ['-datetime_create'],
                'get_latest_by': 'datetime_create',
            },
        ),
    ]
