# Generated by Django 3.0.7 on 2020-07-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='check_mac_value',
        ),
    ]
