# Generated by Django 3.0.7 on 2020-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_payment_check_mac_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-datetime_create']},
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Credit', '信用卡及 GooglePay'), ('GooglePay', 'GooglePay'), ('WebATM', '網路 ATM'), ('ATM', '自動櫃員機'), ('CVS', '超商代碼'), ('BARCODE', '超商條碼'), ('ALL', '不指定付款方式，由綠界顯示付款方式選擇頁面。')], default='Credit', max_length=9),
        ),
    ]
