# Generated by Django 3.0.7 on 2020-07-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品名')),
                ('cat', models.CharField(default='未分類', max_length=200, verbose_name='分類')),
                ('price', models.PositiveIntegerField(default=99999, verbose_name='價格')),
                ('stock', models.PositiveSmallIntegerField(default=0, verbose_name='庫存')),
                ('description', models.TextField(default='', verbose_name='詳細說明')),
                ('is_feature_product', models.BooleanField(default=False, verbose_name='是主打商品')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=200, upload_to='', verbose_name='檔案')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
