# Generated by Django 3.0.7 on 2020-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200702_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='照片簡述'),
        ),
    ]
